main: com.crimsonrpg.admin.CrimsonAdmin

name: CrimsonAdmin
version: 1.0
description: Admin commands for CrimsonRPG.

authors: [AlbireoX, KillerSmurf]
website: http://crimsonrpg.com/

commands:
  
  clearinventory:
    description: clears a player's inventory.
    usage: /clear <target>
    aliases: [cli, cleari, cinventory, clear]
    
  help:
    description: helps a player
    usage: /help
    
  sun:
    description: sets the sun to brightness.
    usage: /sun
    aliases: [sunny, sunner]
  
  bring:
    description: brings a player to you.
    usage: /bring <target>
    aliases: br
    
  fakegamemode:
    description: Fakes a game mode change.
    usage: /fakegamemode <target>
    aliases: fakegm
  
  forceload:
    description: Forces loading of all crimson-related things.
    usage: /forceload
    aliases: fload
  
  forcereload:
    description: Forces reloading of all crimson-related things.
    usage: /forcereload
    aliases: freload
  
  forcesave:
    description: Forces saving of all crimson-related things.
    usage: /forcesave
    aliases: fsave
  
  getpos:
    description: Gets the current position of the player.
    usage: /getpos
    
  item:
    description: spawns an item
    usage: /item material
    aliases: [i, it, item]
    
  customitem:
    description: Spawns a custom item.
    usage: /customitem <name>
    aliases: [citem]
    
  customblock:
    description: Spawns a custom block.
    usage: /customblock <name>
    aliases: [cblock, customb, cb]
    
  setspawn:
    description: sets the worlds spawn.
    usage: /setspawn
    aliases: [ss, sspawn, sets]
  
#  spawn:
#    description: teleports to the spawn
#    usage: /spawn
#    aliases: [sp, spaw]
  
  teleport:
    description: teleports a player to a player.
    usage: /teleport <target> or <target> <target>
    aliases: tp
    
  tpos:
    description: teleports the player to a position
    usage: /teleport <x> <y> <z>
    aliases: [tppos, telep, tps]
